/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table category
	 */
	export class Category extends categoryBase{

		//region Static
		//endregion

		//region Fields
		//endregion

		//region Private Methods
		//endregion

		//region Method
		/**
		 * Gets the metadata about the record
		 *
		 * @returns Object
		 */
		getMetadata(): IRecordMeta {
			return {
				fields: {
					name: {
						text: strings.name,
						type: 'string'
					}
				}
			}
		}
		//endregion

		//region Events
		//endregion

		//region Properties
		//endregion

	}
}