/**
 * Generated by xlatte
 */
module latte{

    /**
     * Record for table task
     */
    export class Task extends taskBase{

        //region Static
        //endregion

        //region Fields
        //endregion

        //region Private Methods
        //endregion

        //region Methods
        //endregion

        //region Events
        //endregion

        //region Properties
        //endregion

    }
}