<?php
/**
 * Stub generated by xlatte
 */
class Category extends categoryBase{

    /**
     * @remote
     * @return Category[]
     */
    public static function catalog(){
        return DL::arrayOf('Category', "
            SELECT *
            FROM category
        ");
    }

    /**
     * Override.
     * @return bool
     */
    public function canDelete()
    {
        return true;
    }
}