<?php
/**
 * Stub generated by xlatte
 */
class Task extends taskBase{

    /**
     * @remote
     * @return Task[]
     */
    public static function catalog(){
        return DL::arrayOf('Task',"
            SELECT *
            FROM task
        ");
    }
}